lqthang2204/BDDDevicesAutomation

ManagementElements/ActionElements.py
ManagementElements/Locator.py
Utilities/ActionScript.py
features/Login.feature
features/orangeHRM-2.feature
features/orangeHRM.feature
features/steps/execure_script.py
resources/pages/orangeHRM/LoginPage.yaml

use script 
And I perform login-page action with override values
| Field      | Value    |
| user-field | Admin    |
| pass-field | KEY.title |
or 
And I perform login-page action with override values
| Field      | Value    |
| user-field | Admin    |
| pass-field | Admin123 |

develop function execute action with overwrite

---

.gitignore
Configuration/configuration_env.py
Configuration/devices.py
Configuration/stage.py
Utilities/ActionScript.py
Utilities/action_android.py
Utilities/action_web.py
Utilities/common.py
Utilities/env_android.py
Utilities/read_configuration.py
config_env.ini
environments.yml
features/Login.feature
features/MobileFeature/Login.feature
features/MobileFeature/idiva.feature
features/MobileFeature/tiki.feature
features/environment.py
features/orangeHRM-2.feature
features/orangeHRM.feature
features/steps/execure_script.py
features/steps/execure_script_web.py
features/techpanda.feature
requirements.txt
resources/pages/General/Common.yaml
resources/pages/google/pageGoogle.yaml
resources/pages/idiva/Home_idiva.yaml
resources/pages/idiva/product_sneaker.yaml
resources/pages/orangeHRM/LoginPage.yaml
resources/pages/tiki/indexTiki.yaml

Improve function read file yaml config before run test

---

.github/workflows/python-package-paralle-with-tagsl.yml
.github/workflows/python-package-parallel.yml
Utilities/action_android.py
Utilities/action_web.py
features/Login.feature
features/MobileFeature/Login.feature
features/MobileFeature/idiva.feature
features/MobileFeature/tiki-mobile.feature
features/environment.py
features/orangeHRM-2.feature
features/orangeHRM.feature
features/techpanda.feature

write log for web and mobile

---

environments.yml
features/MobileFeature/idiva.feature
features/MobileFeature/tiki-mobile.feature
features/steps/execure_script.py
resources/pages/tiki/HomeTiki.yaml

add more script open application

---

features/Login.feature
features/steps/execure_script.py

done
replace from @Given to @step
here is report

fix issue steps-unimplemented

---

README.md
Utilities/action_android.py
Utilities/action_web.py
features/Login.feature
features/MobileFeature/idiva.feature
features/steps/execure_script.py
resources/pages/orangeHRM/LoginPage-Variant.yaml

- BUG - Found when the sequence of Test Step has Dict Key creation but not used in Type command
- Additionally - for Actions step execution, a Login variant was created for providing sample to the users in case they want to have control in the scenario instead of Yaml
- ReadMe updated with more info in - How To execute
- Locator Fix for location-option-inpatient in Login.yaml

BUG - Found when the sequence of Test Step has Dict Key and additional updates

---

Utilities/action_web.py
environments.yml
features/Login.feature
features/steps/execure_script.py
resources/pages/orangeHRM/LoginPage.yaml

- The framework allows verifying the status of multiple elements at the same time.
Example
Report HTML

develop function wait with DataTable - WEB

---

.github/workflows/project-runner-windows.yml
.github/workflows/project-runner.yml
Utilities/action_web.py
features/Login.feature
features/environment.py
features/orangeHRM-2.feature
features/orangeHRM.feature
features/techpanda.feature
launch/RunTest.py
project_runner.py
tags_expr_processor.py

Adding a  new feature for Tags Processor to allow user to write freehand expression. 
And based on the expression, filter the feature files accordingly. It should allow user to provide folder path to feature file or a Feature file or using WildCards
Detailed information available in https://github.com/lqthang2204/Selenium-with-python-behave/issues/26

35 tags processor

---

.gitignore
README.md
Utilities/action_android.py
Utilities/action_web.py
Utilities/common_ui.py
Utilities/read_configuration.py
features/environment.py
features/scenarios/mobile/Login.feature
features/scenarios/mobile/idiva.feature
features/scenarios/mobile/tiki-mobile.feature
features/scenarios/web/IgnoredFile.feature
features/scenarios/web/Login.feature
features/scenarios/web/orangeHRM-2.feature
features/scenarios/web/techpanda.feature
features/steps/execure_script.py
libraries/random_generators.py
project_runner.py
tags_expr_processor.py

Upgraded the Tags Processor to recognize Any Tag which has ~symbol to ignore front of it to ignore
The __main()__ section has been updated with the examples

Upgraded the Tags Processor to recognize Any Tag which has ~symbol to ignore

---

Configuration/api_facets.py
Configuration/stage.py
Utilities/action_web.py
Utilities/read_configuration.py
config_env.ini
environments.yml
features/environment.py
features/scenarios/mobile/Login.feature
features/scenarios/mobile/idiva.feature
features/scenarios/web/Login.feature
features/scenarios/web/orangeHRM-2.feature
features/scenarios/web/orangeHRM.feature
features/scenarios/web/techpanda.feature
features/steps/execure_script.py
remote_config.ini

- Add remote_config.ini file to execute script on saucelabs
- To control execute script on saucelabs, the user can set the status for the field remote-saucelabs is true or false

Add more config execute remote with Saucelabs

---

.gitignore
Utilities/accessibility_report.py
features/environment.py
features/scenarios/web/Login.feature
features/scenarios/web/orangeHRM.feature
features/steps/common_stepdefs.py
requirements.txt
resources/accessibility/AXE_Main_Template.html

Perform Accessibility Testing and produce the Report file 
Also verified in parallel execution mode
Feature : PR-38

Automated Web Accessibility Testing using AXE package

---

.github/workflows/project-runner.yml
Utilities/action_web.py
Utilities/common_ui.py
environments.yml
features/scenarios/web/shadow-element.feature
features/steps/execure_script.py
requirements.txt
resources/pages/chrome/settingpage.yaml

@parallel @web @shadow
Feature: test shadow elements
@mc-chrome-shadow
Scenario: test shadow feature function1
Given I navigate to url CHROME-SETTING
And I change the page spec to settingpage
And I click shadow element import borkmarks
And I click shadow element import button
And I wait 5 seconds
And I click shadow element toogle button
And I wait 5 seconds

add pyshadow package

---

Utilities/action_web.py
Utilities/common_ui.py
environments.yml
features/scenarios/web/IgnoredFile.feature
features/scenarios/web/drag-and-drop.feature
features/steps/execure_script.py
resources/pages/Guru99/demoguru99.yaml
resources/pages/Guru99/index_guru.yaml

- Use script below to scroll to element
1.     And I scroll by java-script to element header-python-tutorial
2.      And I scroll to element python-tutorial with text "Execute Python"
3.      And I scroll to element header-python-tutorial

ADD feature scroll to element when verify and in script gherkin

---

Utilities/action_web.py
Utilities/common_ui.py
environments.yml
features/scenarios/web/Login.feature
features/scenarios/web/drag-and-drop.feature
features/steps/execure_script.py
resources/pages/Guru99/double-example.yaml

User can use scripts below to right click and double click for locator
And I double-click element double-button
And I right-click element right-button

develop function double click and right click for web

---

Utilities/action_android.py
Utilities/action_web.py
Utilities/common_ui.py
capabilities_android_app_demo.json
environments.yml
features/environment.py
features/scenarios/android/Login.feature
features/scenarios/iPhone/safari.feature
features/scenarios/web/Login.feature
features/scenarios/web/drag-and-drop.feature
features/steps/execure_script.py
resources/pages/Guru99/Selenium_Live_Project.yaml
resources/pages/Guru99/double-example.yaml
resources/pages/MyRNDemo/indexRN.yaml

use scripts below  to change Iframe
"And I switch to Iframe iframe-topic"
" And I switch Iframe default"
"And I switch Iframe by index 1"
add feature scroll up, scroll down for mobile (android, ios)
And I scroll up to element product-one
And I scroll down to element product-one

Develop feature switch tab, frame for framework

---

.github/workflows/project-runner-Ios-saucelab.yml
.github/workflows/project-runner-android-saucelab.yml
.github/workflows/project-runner-ios.yml
.github/workflows/project-runner.yml

separate run mobile with saucelabs

---

Utilities/action_android.py
Utilities/common_ui.py
features/environment.py
features/scenarios/iPhone/app-health.feature
features/scenarios/iPhone/safari.feature
features/scenarios/remote/remote.feature
features/scenarios/samples/DateTime.feature
features/scenarios/web/drag-and-drop.feature
features/steps/execure_script.py
features/steps/execute_open_browser.py
features/steps/execute_open_mobile.py
requirements.txt
resources/pages/app_health_ios/detail_health_page.yaml

- add function close web browser with title and index
And I close the tab with index 2
And I close the tab with title "AdBlock is now installed!"

develop feature close app and close web page

---

Utilities/common_ui.py
features/scenarios/web/orangeHRM-2.feature
resources/pages/orangeHRM/LoginPage.yaml

- check if os  is mac  change from CONTROL to COMMAND

add function check os system

---

Utilities/common_ui.py
features/scenarios/iPhone/app-health.feature
resources/pages/app_health_ios/detail_health_page.yaml

add more scenario for mobile

---

.github/workflows/project-runner-macOS.yml
Utilities/action_web.py
Utilities/common_ui.py
environments.yml
features/environment.py
features/scenarios/web/Login.feature
features/scenarios/web/drag-and-drop.feature
features/scenarios/web/option-for-browser.feature
features/scenarios/web/orangeHRM-2.feature
features/steps/execute_open_browser.py
javascripts/scrollToElement.js

fix issues when run on safari browser

---

.github/dependabot.yml
Utilities/action_android.py
Utilities/action_web.py
Utilities/common_ui.py
features/environment.py
features/scenarios/api/fake_rest_api.feature
features/scenarios/api/get_demo.feature
features/scenarios/api/reqres.feature
features/scenarios/web/IgnoredFile.feature
features/scenarios/web/drag-and-drop.feature
features/scenarios/web/get_data_form_api.feature
features/scenarios/web/option-for-browser.feature
features/scenarios/web/shadow-element.feature
features/scenarios/web/techOne.feature
features/scenarios/web/techOneAu.feature
features/steps/api_stepdefs.py
features/steps/execure_script.py
features/steps/execute_open_browser.py
features/steps/execute_open_mobile.py
libraries/api/api_asserts.py
libraries/api/request_core.py
libraries/faker/management_user.py
requirements.txt
resources/pages/chrome/settingpage.yaml
resources/pages/orangeHRM/LoginPage.yaml
resources/pages/techOne/Application_Contents.yaml
resources/pages/techOne/Educational_Background.yaml
resources/pages/techOne/application_data_entry.yaml
resources/pages/techOne/login_t1_page.yaml
resources/pages/techOne/student_detail_page.yaml

enhance functions for framework

---

Utilities/common_ui.py

update common file
